# Generated by Django 5.0.7 on 2025-10-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenter',
            name='username',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
