# Generated by Django 5.0.7 on 2025-10-26 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0002_alter_commenter_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('text', 'Text')], max_length=8)),
                ('mime', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='previews/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='comments_app.comment')),
            ],
            options={
                'indexes': [models.Index(fields=['comment', '-created_at'], name='comments_ap_comment_003062_idx')],
            },
        ),
    ]
